sudo: required
dist: trusty
language: python
matrix:
    include:
        - python: 3.6
          env: KERAS_BACKEND=tensorflow TEST_MODE=DOC
        - python: 3.6
          env: KERAS_BACKEND=tensorflow
        - python: 3.5-dev
          env: KERAS_BACKEND=tensorflow
        - python: 3.6
          env: KERAS_BACKEND=theano THEANO_FLAGS=optimizer=fast_compile
        - python: 3.6
          env: KERAS_BACKEND=cntk PYTHONWARNINGS=ignore
install:
  # code below is taken from http://conda.pydata.org/docs/travis.html
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest pandas
  - source activate test-environment
  - pip install --only-binary=numpy,scipy numpy nose scipy matplotlib h5py theano
  - conda install mkl mkl-service

  # set library path
  - export LD_LIBRARY_PATH=$HOME/miniconda/envs/test-environment/lib/:$LD_LIBRARY_PATH

  # install PIL for preprocessing tests
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install pil;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      conda install Pillow;
    fi


  # install TensorFlow (CPU version).
  - pip install tensorflow
  
  - pip3  install -r requirements.txt
  
  # install cntk
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.3.1-cp27-cp27mu-linux_x86_64.whl;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      pip install https://cntk.ai/PythonWheel/CPU-Only/cntk-2.3.1-cp36-cp36m-linux_x86_64.whl;
    fi

  # install pydot for visualization tests
  - conda install pydot graphviz

  # exclude different backends to measure a coverage for the designated backend only
  - if [[ "$KERAS_BACKEND" != "tensorflow" ]]; then
      echo '    keras/backend/tensorflow_backend.py' >> .coveragerc;
    fi
  - if [[ "$KERAS_BACKEND" != "theano" ]]; then
      echo '    keras/backend/theano_backend.py' >> .coveragerc;
    fi
  - if [[ "$KERAS_BACKEND" != "cntk" ]]; then
      echo '    keras/backend/cntk_backend.py' >> .coveragerc;
    fi

  # detect whether core files are changed or not
  - export CORE_CHANGED=False;
  - for entry in `git diff --name-only HEAD~1`; do if [[ "$entry" == "keras/backend/"* ]] || [[ "$entry" == "keras/engine/"* ]] || [[ "$entry" == "keras/layers/"* ]]; then export CORE_CHANGED=True; fi; done
  - export APP_CHANGED=False;
  - for entry in `git diff --name-only HEAD~1`; do if [[ "$entry" == "keras/applications/"* ]]; then export APP_CHANGED=True; fi; done



# command to run tests
script:
  python HDLTex.py;
